### PR TITLE
Wrapped blocking IO in future with own ExecutionContext

### LINKED ISSUE #186: Race condition/deadlock in StorageService.readPngImageData in streamin-wip branch
Observed Exceptions: 

java.io.IOException: Timeout on waiting for new data
at akka.stream.impl.io.InputStreamAdapter

Depending on server infrastructure (2 vs 4 cores), this Exception is thrown. Possibly because of using the same ExecutionContext for streaming and blocking IO. See https://github.com/akka/akka-http/issues/202

### PR DESCRIPTION
**Pull request by kobmic**
Fixes #186

### CODE REVIEW

File: src/main/scala/se/nimsa/sbx/storage/StorageService.scala [hunk 1]
```diff
@@ -73,26 +77,38 @@ trait StorageService {
...
+    val imageReader = ImageIO.getImageReadersByFormatName("DICOM").next
+    imageReader.setInput(iis)
+    val param = imageReader.getDefaultReadParam.asInstanceOf[DicomImageReadParam]
+    if (windowMin < windowMax) {
+      param.setWindowCenter((windowMax - windowMin) / 2)
+      param.setWindowWidth(windowMax - windowMin)
+    }
+
+    // imageReader.read is blocking, needs to be run outside streams execution context
+    val blockingIoContext = ExecutionContext.fromExecutorService(Executors.newFixedThreadPool(2))
```
Comment (KarlSjostrand) [inline src/main/scala/se/nimsa/sbx/storage/StorageService.scala]: Should this be part of a wider overhaul where we think about blocking IO and what thread pools are used to manage such code? Maybe we could use one thread pool for all such ops. I'm not sure it is a great idea to create a new pool for each call to this method. If we leave it like this we also have to shut the pool down when done, no?

**Comment by kobmic** [comment]
Regarding the size of the fixed threadpool for blocking IO: According to akka docs "The exact size should be fine tuned depending on the workload....Usually a small number around the number of cores is a good default to start from." 
That's why I went for fixed size of 4.
