### PR TITLE
Changed to insert with ignore on duplicate key. Closes #270

### LINKED ISSUE #270: Add series type to series throws exception
Issue probably came from update of Slick. insertOrUpdate on rows consisting of only primary key does not work, at least not with MySQL profile. Not sure if it is a bug in Slick or if insertOrUpdate is not intended for this special case.

### PR DESCRIPTION
**Pull request by fredrik-exini**

### CODE REVIEW

File: src/main/scala/se/nimsa/sbx/seriestype/SeriesTypeDAO.scala [hunk 1]
```diff
@@ -165,8 +167,11 @@ class SeriesTypeDAO(val dbConf: DatabaseConfig[JdbcProfile])(implicit ec: Execut
   }.map(_ => Unit)
 
   def upsertSeriesSeriesType(seriesSeriesType: SeriesSeriesType): Future[SeriesSeriesType] = db.run {
-    seriesSeriesTypes.insertOrUpdate(seriesSeriesType)
-  }.map(_ => seriesSeriesType)
+    seriesSeriesTypes += seriesSeriesType
+  }.map(_ => seriesSeriesType).recover {
+    case _: SQLIntegrityConstraintViolationException => seriesSeriesType //Duplicate key -> series already tagged with series type
```
Comment (KarlSjostrand) [inline src/main/scala/se/nimsa/sbx/seriestype/SeriesTypeDAO.scala]: If I understand this correctly, this exception is thrown when using MySql but not when using H2?

Comment (KarlSjostrand) [reply src/main/scala/se/nimsa/sbx/seriestype/SeriesTypeDAO.scala]: Test fails in MetaDataRoutesTest when adding same series type twice.

Comment (fredrik-exini) [reply src/main/scala/se/nimsa/sbx/seriestype/SeriesTypeDAO.scala]: I suppose this is thrown by the connector so using the broader SQLException might be necessary to cover differences among connectors.
